matrix build testing

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -56,74 +56,75 @@ before_install:
   - $CC --version
 
 install:
-  - if ["$DEPS_RESOLVE_BY" = "manual"]; then
-
+  - if [ "$DEPS_RESOLVE_BY" = "manual" ]; then
+      echo "Resolve library dependencies manually.";
   #############################################################################
   # CMAKE                                                                     #
   #############################################################################
-   export PATH=$CMAKE_ROOT/bin:$PATH;
-   CMAKE_33_FOUND=$(cmake --version | grep " 3\.3\." >/dev/null && { echo 0; } || { echo 1; });
-   if [ $CMAKE_33_FOUND -ne 0 ]; then
-      mkdir -p $CMAKE_ROOT &&
-      cd $CMAKE_ROOT &&
-      travis_retry wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz &&
-      tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz --overwrite &&
-      mv -f cmake-3.3.2-Linux-x86_64/* . &&
-      rm -rf cmake-3.3.2-Linux-x86_64.tar.gz cmake-3.3.2-Linux-x86_64 &&
-      cd -;
-   fi;
-   cmake --version;
+#   export PATH=$CMAKE_ROOT/bin:$PATH;
+#   CMAKE_33_FOUND=$(cmake --version | grep " 3\.3\." >/dev/null && { echo 0; } || { echo 1; });
+#   if [ $CMAKE_33_FOUND -ne 0 ]; then
+#      mkdir -p $CMAKE_ROOT &&
+#      cd $CMAKE_ROOT &&
+#      travis_retry wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz &&
+#      tar -xzf cmake-3.3.2-Linux-x86_64.tar.gz --overwrite &&
+#      mv -f cmake-3.3.2-Linux-x86_64/* . &&
+#      rm -rf cmake-3.3.2-Linux-x86_64.tar.gz cmake-3.3.2-Linux-x86_64 &&
+#      cd -;
+#   fi;
+#   cmake --version;
   #############################################################################
   # BOOST                                                                     #
   #############################################################################
-  export CMAKE_PREFIX_PATH=$BOOST_ROOT:$CMAKE_PREFIX_PATH;
-  # cmake --find-package -DNAME=Boost -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST
-  echo -e "#include <boost/version.hpp>\n#include <iostream>\nint main() { std::cout << BOOST_VERSION << std::endl; return 0; }";
-        | $CXX -I$BOOST_ROOT/include -x c++ - >/dev/null || { echo 0; }
-  ls $BOOST_ROOT;
-  BOOST_FOUND=$([ $(./a.out) -ge $BOOST_MIN ] && { echo 0; } || { echo 1; });
-  if [ $BOOST_FOUND -ne 0 ]; then
-      mkdir -p $BOOST_ROOT &&
-      cd $BOOST_ROOT &&
-      travis_retry wget --no-check-certificate -O boost.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2/download &&
-      tar -xjf boost.tar.bz2 --overwrite &&
-      cd boost_1_61_0 &&
-      echo "using gcc "":"" 6 "":"" /usr/bin/g++-6 ; " >> tools/build/src/user-config.jam &&
-      ./bootstrap.sh toolset=gcc-6 --with-libraries=filesystem,mpi,program_options,system,test,serialization --prefix=$BOOST_ROOT &&
-      echo "using mpi ;" >> tools/build/src/user-config.jam &&
-      ./b2 -j2 -target=shared,static &&
-      ./b2 install &&
-      rm -rf boost.tar.bz2 boost_1_61_0 &&
-      cd $HOME;
-    fi;
+#  export CMAKE_PREFIX_PATH=$BOOST_ROOT:$CMAKE_PREFIX_PATH;
+#  # cmake --find-package -DNAME=Boost -DCOMPILER_ID=GNU -DLANGUAGE=CXX -DMODE=EXIST
+#  echo -e "#include <boost/version.hpp>\n#include <iostream>\nint main() { std::cout << BOOST_VERSION << std::endl; return 0; }";
+#        | $CXX -I$BOOST_ROOT/include -x c++ - >/dev/null || { echo 0; }
+#  ls $BOOST_ROOT;
+#  BOOST_FOUND=$([ $(./a.out) -ge $BOOST_MIN ] && { echo 0; } || { echo 1; });
+#  if [ $BOOST_FOUND -ne 0 ]; then
+#      mkdir -p $BOOST_ROOT &&
+#      cd $BOOST_ROOT &&
+#      travis_retry wget --no-check-certificate -O boost.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.bz2/download &&
+#      tar -xjf boost.tar.bz2 --overwrite &&
+#      cd boost_1_61_0 &&
+#      echo "using gcc "":"" 6 "":"" /usr/bin/g++-6 ; " >> tools/build/src/user-config.jam &&
+#      ./bootstrap.sh toolset=gcc-6 --with-libraries=filesystem,mpi,program_options,system,test,serialization --prefix=$BOOST_ROOT &&
+#      echo "using mpi ;" >> tools/build/src/user-config.jam &&
+#      ./b2 -j2 -target=shared,static &&
+#      ./b2 install &&
+#      rm -rf boost.tar.bz2 boost_1_61_0 &&
+#      cd $HOME;
+#    fi;
   #############################################################################
   # ZMQ                                                                       #
   #############################################################################
-  export CMAKE_PREFIX_PATH=$ZMQ_ROOT:$CMAKE_PREFIX_PATH;
-  echo $CMAKE_PREFIX_PATH;
-  ls $ZMQ_ROOT;
-  if [ ! "$(ls -A $ZMQ_ROOT)" ]; then
-      cd /tmp/ &&
-      travis_retry git clone https://github.com/zeromq/libzmq.git&&
-      travis_retry git clone https://github.com/zeromq/cppzmq.git;
-      cd /tmp/libzmq/ &&
-      ./autogen.sh &&
-      mkdir -p $ZMQ_ROOT &&
-      ./configure --prefix=$ZMQ_ROOT &&
-      make &&
-      make install &&
-      cp /tmp/cppzmq/zmq.hpp $ZMQ_ROOT/include/ &&
-      cp /tmp/cppzmq/zmq_addon.hpp $ZMQ_ROOT/include/;
-    else
-      echo "ZeroMQ directory already exists";
-    fi;
-
+#  export CMAKE_PREFIX_PATH=$ZMQ_ROOT:$CMAKE_PREFIX_PATH;
+#  echo $CMAKE_PREFIX_PATH;
+#  ls $ZMQ_ROOT;
+#  if [ ! "$(ls -A $ZMQ_ROOT)" ]; then
+#      cd /tmp/ &&
+#      travis_retry git clone https://github.com/zeromq/libzmq.git&&
+#      travis_retry git clone https://github.com/zeromq/cppzmq.git;
+#      cd /tmp/libzmq/ &&
+#      ./autogen.sh &&
+#      mkdir -p $ZMQ_ROOT &&
+#      ./configure --prefix=$ZMQ_ROOT &&
+#      make &&
+#      make install &&
+#      cp /tmp/cppzmq/zmq.hpp $ZMQ_ROOT/include/ &&
+#      cp /tmp/cppzmq/zmq_addon.hpp $ZMQ_ROOT/include/;
+#    else
+#      echo "ZeroMQ directory already exists";
+#    fi;
+#
   elif ["$DEPS_RESOLVE_BY" = "conan"]; then
+    echo "Resolve library dependencies using conan.";
   #############################################################################
   # Conan
   #############################################################################
-      pip install --upgrade pip --user;
-      pip install conan --user;
+#      pip install --upgrade pip --user;
+#      pip install conan --user;
   fi
 
 script:
